### ISSUE TITLE
default prettier `printWidth: 120` not work as expected

### ISSUE THREAD

**Issue by HADB** [antfu/eslint-config#572]
### Describe the bug

I found a small bug that the default prettier `printWidth: 120` not work for `css` as pointed here:
https://github.com/antfu/eslint-config/blob/1215d9fd98e4b6fee57453312a22c2340c91f085/src/vender/prettier-types.ts#L7-L12

`printWidth: 120` is only set for `markdown` / `slidev`, others will fallback to use prettier's default `80`.

In the following reproduction project: 
```css
body {
  font-family: 'LXGW WenKai GB', 'LXGW WenKai', '仿宋', 'FangSong', 'STFangsong', 'serif';
}
```
will be formatted to:
```css
body {
  font-family: 'LXGW WenKai GB', 'LXGW WenKai', '仿宋', 'FangSong', 'STFangsong',
    'serif';
}
```

I made a PR to fix this, please take a review.

### Reproduction

https://stackblitz.com/~/github.com/HADB/eslint-config-prettier-printWidth-bug-reproduction?file=assets/styles.css

### System Info

```Shell
None.
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)
